quiz/quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_main.urls')),
]

quiz/quiz_main/urls.py
from django.urls import path
from . import views

app_name = 'quiz_main'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('quiz', views.quiz, name='quiz'),
    path('leaderboard', views.leaderboard, name='leaderboard'),
    path('score', views.score, name="score"),
]

quiz/quiz_main/models.py
from django.db import models

# Create your models here.
class Leaderboard_scores(models.Model):
    username = models.CharField(max_length=255, null=True)
    user_score = models.IntegerField(null=True)

    def __str__(self) -> str:
        return f'{self.username}, score: {self.user_score}'

quiz/quiz_main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *

questions = ['1+1','2+2','3+3','4+4','5+5','6+6','7+7','8+8','9+9','10+10']
answers = [2, 4 , 6, 8, 10, 12, 14, 16, 18, 20]
user_score = 0
question_index_global = 0
username = ''

# Create your views here.
def landing(request):
    global username, user_score, question_index_global

    # Initialize global variables
    user_score = 0
    question_index_global = 0
    username = ''

    # Handle POST request
    if request.method == 'POST':
        # Get the username from the request data
        username = request.POST['username']

        # Redirect to the 'quiz' URL
        return redirect('quiz_main:quiz')

    # Handle GET request
    else:
        # Render the 'quiz_main/landing.html' template
        return render(request, 'quiz_main/landing.html')



def quiz(request):
    # Check if the request method is POST
    if request.method == 'POST':
        # Set the global variables question_index_global user_score
        global question_index_global, user_score

        # Define a nested function to check the user's answer
        def check_answer(question_index):
            # Get the user's answer from the request data
            user_answer = request.POST['answer_box']
            # Check if the user's answer is correct
            if int(user_answer) == answers[question_index]:
                return {'message':'correct', 'result':True}
            else:
                return {'message':'incorrect', 'result':False}

        # Check the user's answer
        answer_check = check_answer(question_index_global)

        # If the answer is correct, increment the user's score and the question index
        if answer_check['result']:
            user_score += 1
            question_index_global += 1
        # If the answer is incorrect, increment the question index
        else:
            question_index_global += 1

        print('Question index:',question_index_global)

        # If the question index is less than 10, render the 'quiz.html' template with the next question and the result of the user's answer
        if not question_index_global == 10:

            context = {
                'next_question' : questions[question_index_global],
                'message' : answer_check['message'],
                'ques_num' : question_index_global+1
            }

            return render(request, 'quiz_main/quiz.html', context=context)

        # If the question index is equal to 10, redirect to the 'score' URL
        else:

            return redirect('quiz_main:score')

    # If the request method is GET, render the 'quiz.html' template with the first question and a message indicating that the quiz has started
    else:
        return render(request, 'quiz_main/quiz.html', {'next_question' : questions[question_index_global], 'message' : 'started','ques_num' : question_index_global+1})
    


def score(request):    # Create a new Leaderboard_scores object with the user's username and score
    new_leaderboard_record = Leaderboard_scores(username=username, user_score=user_score)
    # Save the new Leaderboard_scores object to the database
    new_leaderboard_record.save()

    # Render the 'score.html' template with the user's score
    return render(request, 'quiz_main/score.html', {'score':user_score})
    


def leaderboard(request):
    # Retrieve the top 10 user scores from the database
    user_scores = Leaderboard_scores.objects.all().order_by('-user_score')[:10].values()

    # Render the leaderboard.html template and pass in the user scores as a context variable
    return render(request, 'quiz_main/leaderboard.html', {'table_vals':user_scores})

quiz/quiz_main/templates/quiz_main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script>
        
        document.addEventListener(onload, () => {
            let question_num = ({{ques_num}});
            let user_score = ({{score}})

            if (question_num > 10) {
                alert(`Your score: ${user_score}`);
                window.location.href = "{% url 'quiz_main:leaderboard' %}";
            }
        })

    </script>

    <title>Document</title>
</head>
<body>

    <div class="main_container">

        <div class="question_container">

            <h1 id="question">{{next_question}}</h1>

            <form action="" method="post">

                {% csrf_token %}

                <input type="text" name="answer_box" id="answer_box">

                <input type="submit" value="Submit">

            </form>

        </div>

    </div>
    
</body>
</html>

quiz/quiz_main/templates/quiz_main/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
    
    <title>Document</title>
</head>
<body>

    <div class="main_container">

        <div class="container">

            <h1>Welcome!</h1>

            <h4>This is a 10 question arithmetic quiz</h4>

            <p>Enter your username</p>

            <form action="" method="post">

                {% csrf_token %}

                <input type="text" name="username" id="username" placeholder="Username">

                <input type="submit" value="Start quiz">

            </form>

        </div>

    </div>
    
</body>
</html>

quiz/quiz_main/templates/quiz_main/leaderboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/leaderboard_styles.css' %}">

    <title>Document</title>
</head>
<body>

    <div class="main_container">

        <div class="container">

            <table>

                <th>Username</th>
                <th>Score</th>

                {% for record in table_vals %}

                    <tr>

                        <td>{{record.username}}</td>
                        <td>{{record.user_score}}</td>

                    </tr>

                {% endfor %}
                
            </table>

            <br><br>

            <button onclick="redirect()">Go back to home</button>

        </div>

    </div>
    
    <script>

        function redirect() {
            window.location.href = "{% url 'quiz_main:landing' %}"
        }

    </script>

</body>
</html>

quiz/quiz_main/templates/quiz_main/quiz.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">

    <title>Document</title>
</head>
<body>

    <div class="main_container">

        <div class="container">

            <h1 id="question_num">Question {{ques_num}}</h1>

            <h3 id="question">{{next_question}}</h3>

            <form action="" method="post">

                {% csrf_token %}

                <input type="text" name="answer_box" id="answer_box">

                <input type="submit" value="Submit" onclick="check_if_finish()">

            </form>

        </div>

    </div>
    
</body>
</html>

quiz/quiz_main/templates/quiz_main/score.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/main_styles.css' %}">

    <title>Document</title>
</head>
<body>

    <div class="main_container">

        <div class="container">

            <h2>Score: {{score}}</h2>

            <button onclick="redirect()">Go to leaderboard</button>

        </div>

    </div>

    <script>

        function redirect() {
            window.location.href = "{% url 'quiz_main:leaderboard' %}"
        }

    </script>
    
</body>
</html>